### ISSUE TITLE
Server responded but failed to save

### ISSUE THREAD

**Issue by davidwagner** [Cal-CS-61A-Staff/examtool-web#15]
A student is reporting that they see the error "Server responded but failed to save, please refresh and try again. If this error persists, contact your course staff or use the alternative exam medium."  They say that their Internet is working fine.

How would I approach troubleshooting the cause of this problem?

It looks like the relevant code is in the vicinity of 

https://github.com/Cal-CS-61A-Staff/examtool-web/blob/71946e2f9b91819f02e8adb83983a3d344158552/apps/exam/main.py#L131

and the online code I can see that would cause an unsuccessful return are related to the time.  Do I need to worry about student computers' clocks being set incorrectly?  Are there are other possible causes for this error?

**Comment by rahularya50** [comment]
You can see if their request is reaching the server by running `examtool logs --email <THEIR_EMAIL> --exam <THE_EXAM>`. It will show up, if it is arriving.

If not, the error is being thrown on the client because the network request failed.

**Comment by rahularya50** [comment]
If they see the error just once, then it might be a transient thing with their internet / GCP. If the error is persistent, then something else has gone wrong. If that is the case and they are not showing up in the logs, then I'm fairly confident it's an internet error. If that is the case and they *are* showing up in the logs, then there is a bug in the server.

**Comment by rahularya50** [comment]
The only way a student's clock could cause an issue is if it is non-monotonic. If they submit, then their clock time goes backwards by x seconds, then they will be unable to submit for `min(x, 5 minutes)` because the server will assume their saved response is behind the latest response seen by the server.

**Comment by davidwagner** [comment]
Thank you!  That's good to know.  How do I view the logs?  Are they server-side logs, or are there some client logs I could view?

**Comment by davidwagner** [comment]
Got it, thank you.  I was able to check their clocks by using `examtool save-logs` (which shows both the client timestamp and the server timestamp; that's not reported with `examtool logs` but is with `save-logs`) and rule out clock issues.  Thank you for your help.
